export const SET_AVAILABLE_LIST = 'SET_AVAILABLE_LIST';
export const SET_FILTER_TERM = 'SET_FILTER_TERM';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SET_PAGES = 'SET_PAGES';
export const SET_PREVIEW_ITEM = 'SET_PREVIEW_ITEM';
export const SET_PREVIEW_ITEM_DETAILS = 'SET_PREVIEW_ITEM_DETAILS';
export const SET_SORT_DETAILS = 'SET_SORT_DETAILS';
export const SET_SORT_LIST = 'SET_SORT_LIST';
